In [2]:
import pandas as pd

df_population = pd.read_csv('../../raw/서울시 주민등록인구 (연령별구별) 통계.txt', thousands = ',', sep ='\t',encoding='UTF8',)

df_population.drop(['기간'], axis='columns', inplace=True) 

df_population.replace('-', '0', inplace = True)
df_population.replace('', '0', inplace = True)

In [4]:
df_population['85~89세'] = df_population['85~89세'].str.replace(',', '').astype('int64')
df_population['90~94세'] = df_population['90~94세'].str.replace(',', '').astype('int64')
df_population['95~99세'] = df_population['95~99세'].str.replace(',', '').astype('int64')
df_population['100세 이상'] = df_population['100세 이상'].str.replace(',', '').astype('int64')

In [5]:
df_population_total = df_population.copy()[df_population['구분']=='계']

In [7]:
df_population_total.drop(['구분'], axis='columns', inplace=True)

In [8]:
df_population_total['행정구역별'].replace('합계','서울시', inplace = True)

In [15]:
df_population_total['10대 이하'] = df_population_total['0~4세'] + df_population_total['5~9세'] + df_population_total['10~14세'] + df_population_total['15~19세']
df_population_total['19-44'] = df_population_total['20~24세'] + df_population_total['25~29세'] + df_population_total['30~34세'] + df_population_total['35~39세'] + df_population_total['40~44세']
df_population_total['45-64'] = df_population_total['45~49세'] + df_population_total['50~54세'] + df_population_total['55~59세'] + df_population_total['60~64세']
df_population_total['65-74'] = df_population_total['65~69세'] + df_population_total['70~74세']
df_population_total['70대 이상'] = df_population_total['75~79세'] + df_population_total['80~84세'] + df_population_total['85~89세']+df_population_total['90~94세'] + df_population_total['95~99세']+df_population_total['100세 이상']

In [9]:
cols = df_population_total.columns
df_population_total.drop(cols[2:23], axis = 1,inplace = True)

In [17]:
df_population_total.head()

   행정구역별         계   10대 이하    19-44    45-64   65-74  70대 이상
0    서울시  10010983  1511483  3840945  3173283  883211  602061
3    종로구    161869    21277    61014    52059   14713   12806
6     중구    136488    15979    53831    43403   12915   10360
9    용산구    245185    33152    96832    76410   20719   18072
12   성동구    308979    44259   124318    96455   25425   18522

In [18]:
df_population_total.rename(columns={'행정구역별':'자치구', '계':'주민등록인구'}, inplace=True)
df_population_total.set_index('자치구',inplace=True)

In [19]:
df_population_total

        주민등록인구   10대 이하    19-44    45-64   65-74  70대 이상
자치구
서울시   10010983  1511483  3840945  3173283  883211  602061
종로구     161869    21277    61014    52059   14713   12806
중구      136488    15979    53831    43403   12915   10360
용산구     245185    33152    96832    76410   20719   18072
성동구     308979    44259   124318    96455   25425   18522
광진구     366972    51136   154091   113843   28692   19210
동대문구    363023    49058   143780   110835   34172   25178
중랑구     402024    53808   145653   137399   39563   25601
성북구     454744    71624   169891   142379   40112   30738
강북구     317695    41365   108338   107415   34995   25582
도봉구     335631    48571   112255   116091   33957   24757
노원구     537303    93081   184181   179118   46661   34262
은평구     484546    72872   173808   157128   46767   33971
서대문구    323171    46659   125171    99267   28385   23689
마포구     385925    57523   164304   111669   28858   23571
양천구     462285    86064   158825   156132   38113   23151
강서구     598273    91952   239151   183093   52356   31721
구로구     439371    65031   162899   145662   40895   24884
금천구     251820    31376    93745    89039   23280   14380
영등포구    400986    53353   160534   129227   34050   23822
동작구     408912    57222   167016   122448   36492   25734
관악구     517334    57255   237970   146915   45476   29718
서초구     435107    82568   162598   132805   35305   21831
강남구     550209    99452   211473   168259   44458   26567
송파구     682741   115876   267157   212374   56204   31130
강동구     440390    70970   162110   143858   40648   22804

In [20]:
df_population_total.to_csv("../raw/서울시 주민등록인구 (연령별구별) 통계_2019_Q4.csv", mode='w',encoding = 'utf-8-sig')